In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

# for creating gif-images
import imageio
import os.path

# Read data files

In [2]:
# olympic games data
olympics = pd.read_csv('../olympics/olympics_upd.csv')
olympics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284851 entries, 0 to 284850
Data columns (total 14 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   name        284851 non-null  object
 1   sex         284851 non-null  object
 2   age         275536 non-null  float64
 3   team        284851 non-null  object
 4   noc         284851 non-null  object
 5   games       284851 non-null  object
 6   year        284851 non-null  int64
 7   season      284851 non-null  object
 8   city        284851 non-null  object
 9   sport       284851 non-null  object
 10  event       284851 non-null  object
 11  medal       42220 non-null   object
 12  birth_year  275536 non-null  float64
 13  country     284828 non-null  object
dtypes: float64(2), int64(1), object(11)
memory usage: 30.4+ MB

In [3]:
# setting sort order for 'medal' field (by making 'medal' a Categorical field)
medals_order = ['Bronze', 'Silver', 'Gold']
olympics['medal'] = pd.Categorical(olympics['medal'], medals_order)

# rename column
olympics.rename(columns={'sex': 'gender'}, inplace=True)

In [4]:
# olympic games data
countries = pd.read_csv('../olympics/countries_upd.csv')
countries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   continent  246 non-null    object
 1   region     246 non-null    object
 2   country    246 non-null    object
 3   capital    233 non-null    object
 4   fips       236 non-null    object
 5   iso_2      238 non-null    object
 6   iso_3      239 non-null    object
 7   iso_no     239 non-null    float64
 8   internet   237 non-null    object
 9   note       15 non-null     float64
dtypes: float64(2), object(8)
memory usage: 19.3+ KB

In [5]:
# Adding DECADES to Olympics data
olympics['decade'] = (olympics['year'] // 10) * 10
olympics.sample(5)

,name,gender,age,team,noc,games,year,season,city,sport,event,medal,birth_year,country,decade
243942,Ekaterina Stefanova Dafovska (-Prodanova),F,18.0,Bulgaria,BUL,1994 Winter,1994,Winter,Lillehammer,Biathlon,Biathlon Women's 4 x 7.5 kilometres Relay,NaN,1976.0,Bulgaria,1990
21551,Karin Bormann (-Kusch),F,18.0,West Germany,FRG,1972 Summer,1972,Summer,Munich,Swimming,Swimming Women's 200 metres Backstroke,NaN,1954.0,Germany,1970
61273,Masaya Fukuda,M,22.0,Japan,JPN,1968 Summer,1968,Summer,Mexico City,Fencing,"Fencing Men's Foil, Team",NaN,1946.0,Japan,1960
126558,Cecil Charles McMaster,M,28.0,South Africa,RSA,1924 Summer,1924,Summer,Paris,Athletics,Athletics Men's 10 kilometres Walk,Bronze,1896.0,South Africa,1920
196894,Toshinao Tomie,M,25.0,Japan,JPN,1936 Summer,1936,Summer,Berlin,Athletics,Athletics Men's 800 metres,NaN,1911.0,Japan,1930

# Part 1 - Geting Sports with maximum number of Olympic games

In [6]:
olympics.head(5)

,name,gender,age,team,noc,games,year,season,city,sport,event,medal,birth_year,country,decade
0,A Dijiang,M,24.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,1968.0,China,1990
1,A Lamusi,M,23.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,1989.0,China,2010
2,Gunnar Nielsen Aaby,M,24.0,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,1896.0,Denmark,1920
3,Edgar Lindenau Aabye,M,34.0,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,1866.0,Denmark,1900
4,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,1914.0,Netherlands,1930

In [9]:
# getting sports with all events as separate dataframe

sports_big = olympics[['sport', 'event', 'decade', 'year', 'season', 'city']]
# sports_big.info() # 284851 entries

sports_big.drop_duplicates(inplace=True)
# sports_big.info() # 6537 entries

C:\Users\anast\AppData\Local\Temp\ipykernel_2724\1010914717.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sports.drop_duplicates(inplace=True)

In [11]:
# getting aggregation for 'sport' level only
sports = olympics[['sport', 'decade', 'year', 'season', 'city']]
# sports.info() # 284851 entries

sports.drop_duplicates(inplace=True)
sports.info() # 952 entries

<class 'pandas.core.frame.DataFrame'>
Int64Index: 952 entries, 0 to 243681
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   sport   952 non-null    object
 1   decade  952 non-null    int64
 2   year    952 non-null    int64
 3   season  952 non-null    object
 4   city    952 non-null    object
dtypes: int64(2), object(3)
memory usage: 44.6+ KB

C:\Users\anast\AppData\Local\Temp\ipykernel_2724\2377790289.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sports.drop_duplicates(inplace=True)

### Sports over years

In [25]:
sports_stats_years = sports.groupby(by=['season', 'sport'])['year'].describe()
sports_stats_years.reset_index(inplace=True)
sports_stats_years.sort_values(by='count', ascending=False, inplace=True)
sports_stats_years.head(30)

,season,sport,count,mean,std,min,25%,50%,75%,max
57,Summer,Swimming,30.0,1958.733333,38.974734,1896.0,1925.0,1962.0,1991.0,2020.0
29,Summer,Fencing,30.0,1958.733333,38.974734,1896.0,1925.0,1962.0,1991.0,2020.0
7,Summer,Athletics,30.0,1958.733333,38.974734,1896.0,1925.0,1962.0,1991.0,2020.0
33,Summer,Gymnastics,29.0,1956.620690,37.876127,1896.0,1924.0,1960.0,1988.0,2016.0
48,Summer,Rowing,29.0,1960.896552,37.787323,1900.0,1928.0,1964.0,1992.0,2020.0
20,Summer,Cycling,29.0,1956.620690,37.876127,1896.0,1924.0,1960.0,1988.0,2016.0
69,Summer,Wrestling,29.0,1960.758621,38.024104,1896.0,1928.0,1964.0,1992.0,2020.0
31,Summer,Football,28.0,1961.928571,38.062258,1900.0,1927.0,1966.0,1993.0,2020.0
26,Summer,Diving,28.0,1963.071429,36.585697,1904.0,1931.0,1966.0,1993.0,2020.0
52,Summer,Shooting,28.0,1961.785714,38.418126,1896.0,1930.0,1966.0,1993.0,2020.0
67,Summer,Water Polo,28.0,1962.857143,36.948126,1900.0,1931.0,1966.0,1993.0,2020.0
68,Summer,Weightlifting,27.0,1964.518519,36.658896,1896.0,1934.0,1968.0,1994.0,2020.0
51,Summer,Sailing,27.0,1965.037037,35.770079,1900.0,1934.0,1968.0,1994.0,2020.0
14,Summer,Boxing,26.0,1967.230769,34.539609,1904.0,1939.0,1970.0,1995.0,2020.0
42,Summer,Modern Pentathlon,25.0,1969.920000,32.395885,1912.0,1948.0,1972.0,1996.0,2020.0
28,Summer,Equestrianism,25.0,1965.120000,33.536448,1900.0,1936.0,1968.0,1992.0,2016.0
35,Summer,Hockey,24.0,1971.666667,31.954678,1908.0,1951.0,1974.0,1997.0,2020.0
78,Winter,Ice Hockey,22.0,1972.000000,27.512768,1924.0,1953.0,1974.0,1993.5,2014.0
74,Winter,Cross Country Skiing,22.0,1972.000000,27.512768,1924.0,1953.0,1974.0,1993.5,2014.0
86,Winter,Speed Skating,22.0,1972.000000,27.512768,1924.0,1953.0,1974.0,1993.5,2014.0
76,Winter,Figure Skating,22.0,1972.000000,27.512768,1924.0,1953.0,1974.0,1993.5,2014.0
84,Winter,Ski Jumping,22.0,1972.000000,27.512768,1924.0,1953.0,1974.0,1993.5,2014.0
81,Winter,Nordic Combined,22.0,1972.000000,27.512768,1924.0,1953.0,1974.0,1993.5,2014.0
73,Winter,Bobsleigh,21.0,1972.571429,28.058103,1924.0,1952.0,1976.0,1994.0,2014.0
11,Summer,Basketball,20.0,1981.600000,24.396721,1936.0,1963.0,1982.0,2001.0,2020.0
17,Summer,Canoeing,19.0,1979.578947,23.281647,1936.0,1962.0,1980.0,1998.0,2016.0
70,Winter,Alpine Skiing,19.0,1978.947368,22.532627,1936.0,1962.0,1980.0,1996.0,2014.0
3,Summer,Archery,17.0,1975.294118,40.944726,1900.0,1972.0,1988.0,2004.0,2020.0
61,Summer,Tennis,17.0,1959.176471,50.015292,1896.0,1908.0,1988.0,2004.0,2020.0
66,Summer,Volleyball,15.0,1992.000000,17.888544,1964.0,1978.0,1992.0,2006.0,2020.0

In [26]:
# sports included only once in Olympic games
sports_stats_years_rare = sports_stats_years[sports_stats_years['count']==1]
sports_stats_years_rare.sort_values(by='min', ascending=False, inplace=True)
sports_stats_years_rare

C:\Users\anast\AppData\Local\Temp\ipykernel_2724\2512306442.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sports_stats_years_rare.sort_values(by='min', ascending=False, inplace=True)

,season,sport,count,mean,std,min,25%,50%,75%,max
21,Summer,Cycling BMX Freestyle,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
27,Summer,Equestrian,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
55,Summer,Sport Climbing,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
24,Summer,Cycling Road,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
22,Summer,Cycling BMX Racing,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
39,Summer,Karate,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
41,Summer,Marathon Swimming,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
16,Summer,Canoe Sprint,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
15,Summer,Canoe Slalom,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
53,Summer,Skateboarding,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
10,Summer,Baseball/Softball,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
6,Summer,Artistic Swimming,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
5,Summer,Artistic Gymnastics,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
23,Summer,Cycling Mountain Bike,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
56,Summer,Surfing,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
0,Summer,3x3 Basketball,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
62,Summer,Trampoline Gymnastics,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
25,Summer,Cycling Track,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
1,Summer,Aeronautics,1.0,1936.0,NaN,1936.0,1936.0,1936.0,1936.0,1936.0
71,Winter,Alpinism,1.0,1924.0,NaN,1924.0,1924.0,1924.0,1924.0,1924.0
80,Winter,Military Ski Patrol,1.0,1924.0,NaN,1924.0,1924.0,1924.0,1924.0,1924.0
36,Summer,Ice Hockey,1.0,1920.0,NaN,1920.0,1920.0,1920.0,1920.0,1920.0
37,Summer,Jeu De Paume,1.0,1908.0,NaN,1908.0,1908.0,1908.0,1908.0,1908.0
45,Summer,Racquets,1.0,1908.0,NaN,1908.0,1908.0,1908.0,1908.0,1908.0
43,Summer,Motorboating,1.0,1908.0,NaN,1908.0,1908.0,1908.0,1908.0,1908.0
47,Summer,Roque,1.0,1904.0,NaN,1904.0,1904.0,1904.0,1904.0,1904.0
19,Summer,Croquet,1.0,1900.0,NaN,1900.0,1900.0,1900.0,1900.0,1900.0
18,Summer,Cricket,1.0,1900.0,NaN,1900.0,1900.0,1900.0,1900.0,1900.0
12,Summer,Basque Pelota,1.0,1900.0,NaN,1900.0,1900.0,1900.0,1900.0,1900.0

### Sports over decades

In [27]:
sports_stats_decades = sports.groupby(by=['season', 'sport'])['decade'].describe()
sports_stats_decades.reset_index(inplace=True)
sports_stats_decades.sort_values(by='count', ascending=False, inplace=True)
sports_stats_decades.head(30)

,season,sport,count,mean,std,min,25%,50%,75%,max
57,Summer,Swimming,30.0,1954.666667,39.280892,1890.0,1920.0,1960.0,1987.5,2020.0
29,Summer,Fencing,30.0,1954.666667,39.280892,1890.0,1920.0,1960.0,1987.5,2020.0
7,Summer,Athletics,30.0,1954.666667,39.280892,1890.0,1920.0,1960.0,1987.5,2020.0
33,Summer,Gymnastics,29.0,1952.413793,37.952524,1890.0,1920.0,1960.0,1980.0,2010.0
48,Summer,Rowing,29.0,1956.896552,37.994685,1900.0,1920.0,1960.0,1990.0,2020.0
20,Summer,Cycling,29.0,1952.413793,37.952524,1890.0,1920.0,1960.0,1980.0,2010.0
69,Summer,Wrestling,29.0,1956.551724,38.570516,1890.0,1920.0,1960.0,1990.0,2020.0
31,Summer,Football,28.0,1957.857143,38.331608,1900.0,1920.0,1960.0,1990.0,2020.0
26,Summer,Diving,28.0,1958.928571,37.052444,1900.0,1927.5,1960.0,1990.0,2020.0
52,Summer,Shooting,28.0,1957.857143,38.620388,1890.0,1927.5,1960.0,1990.0,2020.0
67,Summer,Water Polo,28.0,1958.928571,37.052444,1900.0,1927.5,1960.0,1990.0,2020.0
68,Summer,Weightlifting,27.0,1960.370370,37.156786,1890.0,1930.0,1960.0,1990.0,2020.0
51,Summer,Sailing,27.0,1961.111111,35.877284,1900.0,1930.0,1960.0,1990.0,2020.0
14,Summer,Boxing,26.0,1963.076923,35.073549,1900.0,1932.5,1965.0,1990.0,2020.0
42,Summer,Modern Pentathlon,25.0,1966.000000,32.532035,1910.0,1940.0,1970.0,1990.0,2020.0
28,Summer,Equestrianism,25.0,1961.200000,33.080709,1900.0,1930.0,1960.0,1990.0,2010.0
35,Summer,Hockey,24.0,1967.500000,32.604348,1900.0,1947.5,1970.0,1992.5,2020.0
78,Winter,Ice Hockey,22.0,1967.727273,28.103858,1920.0,1950.0,1970.0,1990.0,2010.0
74,Winter,Cross Country Skiing,22.0,1967.727273,28.103858,1920.0,1950.0,1970.0,1990.0,2010.0
86,Winter,Speed Skating,22.0,1967.727273,28.103858,1920.0,1950.0,1970.0,1990.0,2010.0
76,Winter,Figure Skating,22.0,1967.727273,28.103858,1920.0,1950.0,1970.0,1990.0,2010.0
84,Winter,Ski Jumping,22.0,1967.727273,28.103858,1920.0,1950.0,1970.0,1990.0,2010.0
81,Winter,Nordic Combined,22.0,1967.727273,28.103858,1920.0,1950.0,1970.0,1990.0,2010.0
73,Winter,Bobsleigh,21.0,1968.095238,28.743529,1920.0,1950.0,1970.0,1990.0,2010.0
11,Summer,Basketball,20.0,1977.500000,25.105042,1930.0,1960.0,1980.0,2000.0,2020.0
17,Summer,Canoeing,19.0,1975.263158,23.656904,1930.0,1960.0,1980.0,1995.0,2010.0
70,Winter,Alpine Skiing,19.0,1974.736842,23.182470,1930.0,1960.0,1980.0,1990.0,2010.0
3,Summer,Archery,17.0,1971.764706,40.809817,1900.0,1970.0,1980.0,2000.0,2020.0
61,Summer,Tennis,17.0,1955.294118,50.139511,1890.0,1900.0,1980.0,2000.0,2020.0
66,Summer,Volleyball,15.0,1988.000000,18.593394,1960.0,1975.0,1990.0,2000.0,2020.0

In [29]:
# sports included only once in Olympic games
sports_stats_decades_rare = sports_stats_decades[sports_stats_decades['count']==1]
sports_stats_decades_rare.sort_values(by='min', ascending=False, inplace=True)
sports_stats_decades_rare

C:\Users\anast\AppData\Local\Temp\ipykernel_2724\4157960968.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sports_stats_decades_rare.sort_values(by='min', ascending=False, inplace=True)

,season,sport,count,mean,std,min,25%,50%,75%,max
21,Summer,Cycling BMX Freestyle,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
53,Summer,Skateboarding,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
25,Summer,Cycling Track,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
55,Summer,Sport Climbing,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
24,Summer,Cycling Road,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
22,Summer,Cycling BMX Racing,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
39,Summer,Karate,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
41,Summer,Marathon Swimming,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
16,Summer,Canoe Sprint,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
15,Summer,Canoe Slalom,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
10,Summer,Baseball/Softball,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
6,Summer,Artistic Swimming,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
5,Summer,Artistic Gymnastics,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
23,Summer,Cycling Mountain Bike,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
56,Summer,Surfing,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
0,Summer,3x3 Basketball,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
62,Summer,Trampoline Gymnastics,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
27,Summer,Equestrian,1.0,2020.0,NaN,2020.0,2020.0,2020.0,2020.0,2020.0
1,Summer,Aeronautics,1.0,1930.0,NaN,1930.0,1930.0,1930.0,1930.0,1930.0
36,Summer,Ice Hockey,1.0,1920.0,NaN,1920.0,1920.0,1920.0,1920.0,1920.0
71,Winter,Alpinism,1.0,1920.0,NaN,1920.0,1920.0,1920.0,1920.0,1920.0
80,Winter,Military Ski Patrol,1.0,1920.0,NaN,1920.0,1920.0,1920.0,1920.0,1920.0
37,Summer,Jeu De Paume,1.0,1900.0,NaN,1900.0,1900.0,1900.0,1900.0,1900.0
19,Summer,Croquet,1.0,1900.0,NaN,1900.0,1900.0,1900.0,1900.0,1900.0
18,Summer,Cricket,1.0,1900.0,NaN,1900.0,1900.0,1900.0,1900.0,1900.0
45,Summer,Racquets,1.0,1900.0,NaN,1900.0,1900.0,1900.0,1900.0,1900.0
47,Summer,Roque,1.0,1900.0,NaN,1900.0,1900.0,1900.0,1900.0,1900.0
12,Summer,Basque Pelota,1.0,1900.0,NaN,1900.0,1900.0,1900.0,1900.0,1900.0
43,Summer,Motorboating,1.0,1900.0,NaN,1900.0,1900.0,1900.0,1900.0,1900.0